site_name: Troussse TI pour les Attestations
repo_url: https://github.com/GuillaumeBourque-QC/trousse-techno
repo_name: GuillaumeBourque-QC/trousse-techno

theme:
  name: material
  logo: assets/Québec_blanc.svg
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - scheme: qc-piv
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Basculer en mode sombre
    - scheme: qc-piv-sombre
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Basculer en mode clair
extra_css:
  - stylesheets/extra.css


nav:
  - Accueil: index.md
  - Gouvernance:
    - Gouvernance: gouvernance/index.md
    - Définitions: gouvernance/definitions.md
    - Réglementation: gouvernance/reglementation.md
    - Collaboration: gouvernance/collaboration.md
  - Attestations:
    - Attestations: attestations/index.md
    - Emetteurs: attestations/emetteur.md
    - Vérificateurs: attestations/verificateur.md
