site_name: Troussse TI pour les Attestations
repo_url: https://github.com/GuillaumeBourque-QC/trousse-TI
repo_name: GuillaumeBourque-QC/trousse-TI

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Basculer en mode sombre
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Basculer en mode clair

nav:
  - Accueil: index.md
  - Gouvernance:
    - Gouvernance: gouvernance/index.md
    - Définitions: gouvernance/definitions.md
    - Réglementation: gouvernance/reglementation.md
    - Collaboration: gouvernance/collaboration.md
  - Attestations:
    - Attestations: attestations/index.md
    - Emetteurs: attestations/emetteur.md
    - Vérificateurs: attestations/verificateur.md
